### ISSUE TITLE
Blog post refers to ember-usable

### ISSUE THREAD

**Issue by ef4** [pzuraq/ember-could-get-used-to-this#12]
The [intro blog post](https://www.pzuraq.com/introducing-use/) is showing things imported from `ember-usable`, but I think that was just a working name for what is now `ember-could-get-used-to-this`.

**Comment by ef4** [comment]
(Also the package.json repository field here.)

**Comment by boris-petrov** [comment]
There is also a typo - `(concat "www.example.com/users" @userId)` should be `(concat "www.example.com/users/" @userId)`.

**Comment by pzuraq** [comment]
Thanks! Have updated the blog post, will submit a fix for the package repository
