### ISSUE TITLE
Uncaught Error: Could not find module `@ember/helper` imported from `ember-could-get-used-to-this/-private/functions`

### ISSUE THREAD

**Issue by chrism** [pzuraq/ember-could-get-used-to-this#20]
Hi,

After installing via
```
ember install ember-could-get-used-to-this
```

the site builds but I’m getting this error in the console.

```
loader.js:247 Uncaught Error: Could not find module `@ember/helper` imported from `ember-could-get-used-to-this/-private/functions`
    at missingModule (loader.js:247)
    at findModule (loader.js:258)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at requireModule (loader.js:24)
    at r (loader.js:176)
```

This is before adding any new code.

Ember CLI : 3.20
Ember : 3.20.3

Removing the addon and everything is working as expected again.

Am I missing something? Thanks.

**Comment by pzuraq** [comment]
This addon only works on the latest beta currently, it's based on brand new features

**Comment by chrism** [comment]
Ah sorry I didn’t realise that. Thanks.

**Comment by NullVoxPopuli** [comment]
I'm using canary here: https://github.com/NullVoxPopuli/ember-three-boxes-demo/pull/212/files#diff-e84aa6f1f31cf2b99ff36d2934039b0733b2acc69fc17e23ae324b51c2e524b4R7

and have the same error about `@ember/helper`

**Comment by pzuraq** [comment]
@NullVoxPopuli you also need the latest ember-cli-babel, to get the latest modules transform

**Comment by NullVoxPopuli** [comment]
I am using the latest - 7.23.0

**Comment by pzuraq** [comment]
@NullVoxPopuli is it the error mentioned above specifically? Because `@ember/helper` should be transformed to `Ember._setHelperManager`, so you would get something like "Ember._setHelperManager is not a function" if the transform was working

**Comment by NullVoxPopuli** [comment]
it is the same, yes. :D 

It turns out the issue was my lockfile. somehow I didn't get a warning about mismatched deps or something.
nuking the lockfile and reinstalling from scratch solved the issue.
