### ISSUE TITLE
Ember._helperManagerCapabilities is not a function

### ISSUE THREAD

**Issue by JamesWilmot** [pzuraq/ember-could-get-used-to-this#21]
Trying to experiment with this in an add-on and in the dummy app I get the following in console:

`Uncaught TypeError: Ember._helperManagerCapabilities is not a function
    at new FunctionalHelperManager (functions.js:8)` 

Really looking forward to fiddling with this as it seems to solve a number of issues that we've solved badly in a few different ways!

**Comment by buschtoens** [comment]
https://github.com/pzuraq/ember-could-get-used-to-this/issues/20#issuecomment-720623234

> This addon only works on the latest beta currently, it's based on brand new features

The README states incorrect support.

**Comment by JamesWilmot** [comment]
@buschtoens thanks!
