### ISSUE TITLE
Conditional use resource

### ISSUE THREAD

**Issue by josemarluedke** [pzuraq/ember-could-get-used-to-this#8]
I'm playing with this lib (the initial-implementation branch) and I'm wondering how to get a `@use` with a conditional.

I have a set of logic deciding when to fetch the data, but using the decorator alone doesn't seem to be possible to decide if I should execute my resource.  Looking at the RFC, the `useResource` might be a good option. However, I still need to get the state in "tracked matter".  Maybe a combination of effect and useResource?

Any help here would be awesome, as I experiment with use & resources. 

Here is a high-level example: 

// Works!
```
class MyComponent extends Componnet {
  @use accounts = watchQuery(this.args.myArgs);
}
```

// Well, just something that will not work... 

```
class MyComponent extends Componnet {
  @tracked accounts; // ???

  constructor(owner, args) {
    super(owner, args);

    this.accounts = use(
      this,
      watchQuery(() => [
         ...this.args.myArgs
      ])
    ).state;

    console.log(this.accounts);
  }
}
```

PS, this `watchQuery` resource is an Apollo GraphQL thing that I'm working on..  Here is a sketch of that resource: https://gist.github.com/josemarluedke/2e60b6d7303d4eb4fdfbba157e11dc34

**Comment by pzuraq** [comment]
Sorry I left this for so long! I've updated with a new API in general and finally gotten it out the door.

So the issue you're trying to solve is, you want to conditionally load data based on another argument?

**Comment by josemarluedke** [comment]
Yeah, I just catching up with the changes (great blog post btw). Yes, my original motivation was to load the data depending on another argument/tracked property.

However, as I worked more on this, I think my original issue is not valid. Looking around in the React ecosystem, they usually solve this issue by returning a function from the hook that would trigger the underlining `resource` to load. Here is an example that I still need to test out to see if works with this addon:

```js
class MyComponent extends Componnet {
  @use myData = lazyFetchData({id: this.args.id });

  @action loadMyData() {
    this.myData.load();
  }
}
```

Another way is to have an `isEnabled` argument:

```js
class MyComponent extends Componnet {
  @tracked shouldLoad = false
  @use myQuery = fetchData({ isEnabled: this.shouldLoad, id: this.args.id });

  @action loadMyData() {
    this.shouldLoad = true
  }
}
```

Anyway, I don't think this is an issue anymore. Thanks for getting back to me.
